name: headspace_interview
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  http: ^1.3.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  flutter_card_swiper: ^7.0.0
  intl:
  equatable: ^2.0.7
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  integration_test:
    sdk: flutter


flutter:

  uses-material-design: true

        
    
    
                                      